spring.data.mongodb.uri=mongodb+srv://munirabouzenni_db_user:moonstruck99@biblioteca.enmxsi0.mongodb.net/sistema_ingressos?retryWrites=true&w=majority&appName=Biblioteca
spring.data.mongodb.database=sistema_ingressos

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

server.port=8080

logging.level.org.mongodb.driver=WARN
