# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://munirabouzenni_db_user:Moonstruck99@biblioteca.enmxsi0.mongodb.net/sistema_ingressos

# App
spring.application.name=sistema-ingressos
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
